name: mil
channels:
  - pytorch
  - nvidia
dependencies:
  - python==3.11.5
  - pytorch=2.1.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - torchvision=0.16.0=py311_cu118
  - pip
  - pip:
    - tqdm==4.66.1
    - Pillow==10.0.1
    - numpy==1.26.0
    - pandas==2.1.3
    - lightning==2.1.2
    - torchmetrics==1.2.0
    - PyYAML==6.0
    - setuptools==68.0.0
    - scikit-learn==1.3.2